name: Deploy to EKS

on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string
      tag:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      cluster-name:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  eks-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Print received inputs
        run: |
          echo "Application Name: ${{ inputs.application-name }}"
          echo "Tag: ${{ inputs.tag }}"
          echo "AWS Region: ${{ inputs.aws-region }}"
          echo "EKS Cluster Name: ${{ inputs.cluster-name }}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ inputs.aws-region }} --name ${{ inputs.cluster-name }}
      - name: Replace image URL in deployment.yml
        run: |
          sed -i 's|<IMAGE_URL>|${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.application-name }}:${{ inputs.tag }}|g' k8s/deployment.yml
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml
          kubectl apply -f k8s/ingress.yml