name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      application-name:
        description: 'Application Name'
        required: true
        type: string
      tag:
        description: 'Tag'
        default: 'latest'
        required: true
        type: string
      dockerfile:
        description: 'Dockerfile Name'
        default: 'Dockerfile'
        required: true
        type: string
      aws-region:
        description: 'AWS Region'
        default: 'ap-south-1'
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Print received inputs
        run: |
          echo "Application Name: ${{ inputs.application-name }}"
          echo "Tag: ${{ inputs.tag }}"
          echo "Dockerfile Name: ${{ inputs.dockerfile }}"
          echo "AWS Region: ${{ inputs.aws-region }}"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ inputs.aws-region }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com
      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.application-name }}:${{ inputs.tag }} -f ${{ inputs.dockerfile }} .
      - name: Push Docker image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.application-name }}:${{ inputs.tag }}